language: php

php:
  - '7.1'
  - '7.2'

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer update ${COMPOSER_OPTS}

script:
    - vendor/bin/phpunit
    - vendor/bin/infection --min-covered-msi=95 --only-covered --threads=4
