language: php

php:
  - '7.1'
  - '7.2'
  - 'hhvm'

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_script:
  - composer self-update
  - composer update

script:
    - vendor/bin/phpunit
    - vendor/bin/infection --min-covered-msi=95 --only-covered
